baseURL = 'https://meatymeets.github.io'
languageCode = 'en-us'
title = 'Hassle-free way to join, prep and engage in meetings'
[params]
    install_url = 'https://chrome.google.com/webstore/detail/meaty-meets/ajpohkekgaabafinjmabdmnmkddjfpin'
